class AppLocalizations {
  final String locale;
  AppLocalizations(this.locale);

  static const Map<String, Map<String, String>> _strings = {
    'ar': {
      'app_title': 'مسار الائمة',
      'habit_tracker': 'سلسلة النور',
      'tasbih_adhkar': 'المسبحة والأذكار',
      'settings': 'الإعدادات',
      'location': 'الموقع الجغرافي',
      'calculation_method': 'طريقة الحساب',
      'sect_path': 'المذهب / المسار',
      'athkar': 'الأذكار',
      'athkar_morning': 'أذكار الصباح',
      'athkar_evening': 'أذكار المساء',
      'athkar_after_prayer': 'أذكار بعد الصلاة',
      'athkar_before_sleep': 'أذكار النوم',
      'athkar_wakeup': 'أذكار الاستيقاظ',
      'qiyam_dashboard': 'لوحة القيام',
      'countdown_qiyam': 'موعد القيام',
      'countdown_stop': 'انتهاء القيام',
      'countdown_fajr': 'أذان الفجر',
      'qiyam_ended': 'انتهى قيام هذه الليلة',
      'selected_night': 'عرض أوقات ليلة مختارة',
      'prayer_1': '1. النوم الأول (العشاء)',
      'prayer_2': '🌟 2. استيقظ للقيام',
      'prayer_3': '3. سحر / نوم أخير',
      'duration': 'المدة',
      'hours': 'ساعة',
      'minutes': 'دقيقة',
      'start_qiyam_mode': 'بدء وضع القيام',
      'set_alarm': 'ضبط المنبه الآن',
      'alarm_set_success': 'تم ضبط المنبه بنجاح',
      'alarm_set_fail': 'لم نتمكن من ضبط المنبه تلقائياً',
      'qiyam_time': 'وقت القيام',
      'until': 'حتى',
      'fajr': 'الفجر',
      'dhuhr': 'الظهر',
      'asr': 'العصر',
      'maghrib': 'المغرب',
      'daily_prayers': 'الصلوات اليومية',
      'dawood_reminders': 'تذكيرات الأدعية',
      'dawood_reminders_desc': 'إشعارات بأدعية ومناجاة مختارة',
      'system_optimizations': 'تحسينات النظام',
      'battery_optimization': 'تجاهل تحسين البطارية',
      'battery_desc': 'ضروري لضمان عمل الأذان في الخلفية',
      'exact_alarm': 'تراخيص المنبه الدقيق',
      'exact_alarm_desc': 'لضمان دقة توقيت الصلاة',
      'check_permissions': 'فحص الأذونات',
      'qibla_compass': 'اتجاه القبلة',
      'qibla_not_supported': 'الجهاز لا يدعم حساسات القبلة',
      'offset_from_north': 'الانحراف عن الشمال',
      'names_of_allah': 'أسماء الله الحسنى',
      'more_features': 'المزيد من الخدمات',
      'profile': 'ملف المستخدم',
      'guest': 'ضيف',
      'login_to_save': 'سجل دخولك لحفظ بياناتك',
      'google_login': 'تسجيل الدخول باستخدام جوجل',
      'phone_login': 'تسجيل الدخول برقم الهاتف',
      'logout': 'تسجيل الخروج',
      'preferences': 'التفضيلات',
      'language': 'اللغة',
      'daily_reminders': 'التنبيهات اليومية',
      'daily_reminders_desc': 'تذكير بموعد قيام الليل يومياً',
      'font_size': 'حجم الخط',
      'dnd_mode': 'وضع الهدوء (DND)',
      'dnd_desc': 'تفعيل وضع الصامت تلقائياً',
      'dnd_subdesc': 'يتم تفعيل الصامت خلال ساعات النوم والقيام',
      'gps_fetch': 'تحديد موقعي الحالي (GPS)',
      'manual_search': 'بحث يدوي (مثلاً: القاهرة، لندن...)' ,
      'about_app': 'عن التطبيق والمطور',
      'developer': 'المطور',
      'version': 'الإصدار',
      'about_desc': 'تطبيق مسار الائمة يساعدك على ضبط المواقيت والعبادات بدقة، مع أدوات عملية للذكر والمتابعة.\n\nهذا التطبيق صدقة جارية للمرحوم محمد التميمي. نسألكم الدعاء، والحمد لله رب العالمين.',
      'close': 'إغلاق',
      'click_to_log': 'اضغط على اليوم لتسجيل قيامك',
      'streak_days': 'ليلة متواصلة',
      'streak_title': 'الليالي المحياة (التتابع)',
      'tasbih_tap': 'انقر في أي مكان للتسبيح',
      'return_to_tasbih': 'العودة للتسبيح',
      'wakeup_adhkar': 'أذكار الاستيقاظ',
      'login_page_title': 'إنشاء حساب جديد',
      'or': 'أو',
      'enter_phone': 'أدخل رقم الهاتف',
      'send_code': 'إرسال الرمز',
      'verify_code': 'تأكيد الرمز',
      'have_account': 'لديك حساب؟ سجل دخولك',
      'no_account': 'ليس لديك حساب؟ أنشئ حساباً جديداً',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'invalid_email': 'البريد الإلكتروني غير صالح',
      'invalid_password': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
      'reset_defaults': 'إعادة تعيين الإعدادات',
      'reset_done': 'تمت استعادة الإعدادات الافتراضية',
    },
    'en': {
      'app_title': 'Path of the Imams',
      'habit_tracker': 'Chain of Light',
      'tasbih_adhkar': 'Tasbih & Adhkar',
      'settings': 'Settings',
      'location': 'Location',
      'calculation_method': 'Calculation Method',
      'sect_path': 'Sect / Path',
      'athkar': 'Athkar',
      'athkar_morning': 'Morning Athkar',
      'athkar_evening': 'Evening Athkar',
      'athkar_after_prayer': 'After Prayer Athkar',
      'athkar_before_sleep': 'Before Sleep Athkar',
      'athkar_wakeup': 'Wake-up Athkar',
      'qiyam_dashboard': 'Qiyam Dashboard',
      'countdown_qiyam': 'Qiyam Time',
      'countdown_stop': 'End of Qiyam',
      'countdown_fajr': 'Fajr Adhan',
      'qiyam_ended': 'Qiyam ended for tonight',
      'selected_night': 'Showing selected night times',
      'prayer_1': '1. First Sleep (Isha)',
      'prayer_2': '🌟 2. Wake up for Qiyam',
      'prayer_3': '3. Sahar / Final Sleep',
      'duration': 'Duration',
      'hours': 'h',
      'minutes': 'm',
      'start_qiyam_mode': 'Start Qiyam Mode',
      'set_alarm': 'Set Alarm Now',
      'alarm_set_success': 'Alarm set successfully',
      'alarm_set_fail': 'Could not set alarm automatically',
      'qiyam_time': 'Qiyam Time',
      'until': 'until',
      'fajr': 'Fajr',
      'dhuhr': 'Dhuhr',
      'asr': 'Asr',
      'maghrib': 'Maghrib',
      'daily_prayers': 'Daily Prayers',
      'dawood_reminders': 'Supplication Reminders',
      'dawood_reminders_desc': 'Notifications for selected supplications',
      'system_optimizations': 'System Optimizations',
      'battery_optimization': 'Ignore Battery Optimization',
      'battery_desc': 'Required for background Athan playback',
      'exact_alarm': 'Exact Alarm Permission',
      'exact_alarm_desc': 'Ensures precise prayer timing',
      'check_permissions': 'Check Permissions',
      'qibla_compass': 'Qibla Compass',
      'qibla_not_supported': 'Device does not support Qibla sensors',
      'offset_from_north': 'Offset from North',
      'names_of_allah': '99 Names of Allah',
      'more_features': 'More Features',
      'profile': 'User Profile',
      'guest': 'Guest',
      'login_to_save': 'Login to save your data',
      'google_login': 'Sign in with Google',
      'phone_login': 'Sign in with Phone',
      'logout': 'Logout',
      'preferences': 'Preferences',
      'language': 'Language',
      'daily_reminders': 'Daily Reminders',
      'daily_reminders_desc': 'Remind me of Qiyam time daily',
      'font_size': 'Font Size',
      'dnd_mode': 'Do Not Disturb (DND)',
      'dnd_desc': 'Auto Silent Mode',
      'dnd_subdesc': 'Silences phone during sleep & Qiyam',
      'gps_fetch': 'Fetch Current Location (GPS)',
      'manual_search': 'Manual Search (e.g. Cairo, London...)',
      'about_app': 'About App & Developer',
      'developer': 'Developer',
      'version': 'Version',
      'about_desc': 'Path of the Imams helps you stay aligned with prayer timings and daily worship, with practical tools for remembrance and tracking.\n\nThis app is a Sadaqah Jariyah (ongoing charity) for Muhammad Al-Tamimi. Please remember us in your prayers. Praise be to Allah.',
      'close': 'Close',
      'click_to_log': 'Tap on a day to log your Qiyam',
      'streak_days': 'nights streak',
      'streak_title': 'Revived Nights (Sequence)',
      'tasbih_tap': 'Tap anywhere to count',
      'return_to_tasbih': 'Back to Tasbih',
      'wakeup_adhkar': 'Wake-up Adhkar',
      'login_page_title': 'Create New Account',
      'or': 'OR',
      'enter_phone': 'Enter Phone Number',
      'send_code': 'Send Code',
      'verify_code': 'Verify Code',
      'have_account': 'Have an account? Login',
      'no_account': 'Don\'t have an account? Register',
      'email': 'Email',
      'password': 'Password',
      'login': 'Login',
      'register': 'Register',
      'invalid_email': 'Invalid email address',
      'invalid_password': 'Password must be at least 6 characters',
      'reset_defaults': 'Reset to Defaults',
      'reset_done': 'Settings reset to defaults',
    }
  };

  String translate(String key) {
    return _strings[locale]?[key] ?? key;
  }
}
